## Q1. Numpy Array Operations

1. Create a 1-D numpy (`arr_1d`) array with numbers (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71)

In [1]:
import numpy as np

# your code here
arr_1d=np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71]);arr_1d

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71])

2. Compute the sum of squared errors of `arr_1d`.

In [4]:
# your code here
sum((arr_1d-np.mean(arr_1d))**2)

9590.95

3. show all elements of `arr_1d` that are at odd-indices.

In [7]:
# your code here
arr_1d[np.arange(1,len(arr_1d),2)]

array([ 3,  7, 13, 19, 29, 37, 43, 53, 61, 71])

4. show all elements of `arr_1d` that are larger than 40.

In [8]:
# your code here
arr_1d[arr_1d>40]

array([41, 43, 47, 53, 59, 61, 67, 71])

5. show all elements of `arr_1d` at even-indices and smaller than 40.

In [11]:
# your code here
# Create a boolean mask for even indices
even_indices_mask = np.arange(len(arr_1d)) % 2 == 0

# Use the mask to select elements at even indices
selected_elements = arr_1d[even_indices_mask]

# Filter elements smaller than 40
result = selected_elements[selected_elements < 40];result

array([ 2,  5, 11, 17, 23, 31])

6. Create a 2-d array of which the first column contains elements of `arr_1d` at even-indices and the second column contains elements of `arr_1d` at odd-indices.

In [26]:
# your code here
two_column_array = np.zeros((len(arr_1d)//2,2))
# Create a 2D array with two columns
two_column_array[:,0]=arr_1d[np.arange(0,len(arr_1d),2)]
two_column_array[:,1]=arr_1d[np.arange(1,len(arr_1d),2)]
two_column_array

array([[ 2.,  3.],
       [ 5.,  7.],
       [11., 13.],
       [17., 19.],
       [23., 29.],
       [31., 37.],
       [41., 43.],
       [47., 53.],
       [59., 61.],
       [67., 71.]])

7. Using `arr_1d` create a 2-d array of shape (5,4), `arr_2d`.

In [27]:
# your code here
arr_2d = arr_1d.reshape(5,4);arr_2d

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [23, 29, 31, 37],
       [41, 43, 47, 53],
       [59, 61, 67, 71]])

8. Add the array of the first 4 elements of `arr_1d` to each row of `arr_2d`.

In [38]:
# your code here
arr_2d+arr_1d[:4]

array([[ 4,  6, 10, 14],
       [13, 16, 22, 26],
       [25, 32, 36, 44],
       [43, 46, 52, 60],
       [61, 64, 72, 78]])

9. Add the array of the last 5 elements of `arr_1d` to each column of `arr_2d`.

In [41]:
# your code here
arr_2d+arr_1d[-5:][:,np.newaxis]

array([[ 55,  56,  58,  60],
       [ 70,  72,  76,  78],
       [ 84,  90,  92,  98],
       [108, 110, 114, 120],
       [130, 132, 138, 142]])

10. Create the new 2-D array of shape (5,5), denoted `arr_2d_new,` by appending the first 5 elements of `arr_1d` to `arr_2d`.

In [46]:
# your code here
arr_2d_new=np.append(arr_2d,arr_1d[:5].reshape(5,1),axis=1);arr_2d_new

array([[ 2,  3,  5,  7,  2],
       [11, 13, 17, 19,  3],
       [23, 29, 31, 37,  5],
       [41, 43, 47, 53,  7],
       [59, 61, 67, 71, 11]])

10. Compute the row-wise sum of `arr_2d_new`

In [47]:
# your code here
arr_2d_new.sum(axis=1)

array([ 19,  63, 125, 191, 269])

11. Compute the column-wise sum of `arr_2d_new`

In [48]:
# your code here
arr_2d_new.sum(axis=0)

array([136, 149, 167, 187,  28])

## Q2. Approximation of the Sine Functions

It is well known that the sine function can be approximated by the infinite order of the Maclaurin series: $$\sin{x} = x - \dfrac{x^3}{3!} + \dfrac{x^5}{5!} - \dfrac{x^7}{7!} \cdots = \sum_{n=0}^{\infty } \dfrac {(-1)^n}{(2n+1)!} x^{2n+1}$$


1. Write a **lambda function** to approximate $\sin{x}$ with the $N^{th}$ order Maclaurin series.


In [49]:
# your code here

import math
sinx = lambda x, N: sum(((-1)**n) * (x**(2*n + 1)) / math.factorial(2*n + 1) for n in range(N+1))

2. Set $N=5$ and compute $\sin{x}$ where $x$ is eqeually spaced array of 50 numbers in the interval $[-2\pi, 2\pi]$.

In [50]:
# your code here
N=5
x=np.linspace(math.pi*-2,math.pi*2,50)
sinx(x,N)

array([ 3.19507604,  2.13780826,  1.57544065,  1.30403126,  1.18669216,
        1.13376423,  1.0887998 ,  1.01876193,  0.90720602,  0.74950786,
        0.54944865,  0.31666716,  0.06464799, -0.19096176, -0.433823  ,
       -0.64821176, -0.82016831, -0.93846764, -0.99537899, -0.98718177,
       -0.91441262, -0.78183148, -0.59811053, -0.375267  , -0.12787716,
        0.12787716,  0.375267  ,  0.59811053,  0.78183148,  0.91441262,
        0.98718177,  0.99537899,  0.93846764,  0.82016831,  0.64821176,
        0.433823  ,  0.19096176, -0.06464799, -0.31666716, -0.54944865,
       -0.74950786, -0.90720602, -1.01876193, -1.0887998 , -1.13376423,
       -1.18669216, -1.30403126, -1.57544065, -2.13780826, -3.19507604])

3. Compute the approximation errors for the function that you wrote above by comparing the values from your function and those from the sine function in the Numpy library.

In [55]:
# your code here
(np.sin(x)-sinx(x,N))


array([-3.19507604e+00, -1.88415368e+00, -1.08472310e+00, -6.08348705e-01,
       -3.31549395e-01, -1.75096376e-01, -8.93135835e-02, -4.38340225e-02,
       -2.06067159e-02, -9.22986066e-03, -3.91375106e-03, -1.55894515e-03,
       -5.77773387e-04, -1.96872099e-04, -6.07441055e-05, -1.66388871e-05,
       -3.94074210e-06, -7.78181567e-07, -1.21631610e-07, -1.39158558e-08,
       -1.02780773e-09, -3.92752497e-11, -4.95603558e-13, -6.66133815e-16,
        0.00000000e+00, -2.77555756e-17,  6.66133815e-16,  4.95603558e-13,
        3.92752497e-11,  1.02780795e-09,  1.39158558e-08,  1.21631610e-07,
        7.78181567e-07,  3.94074210e-06,  1.66388871e-05,  6.07441055e-05,
        1.96872099e-04,  5.77773387e-04,  1.55894515e-03,  3.91375106e-03,
        9.22986066e-03,  2.06067159e-02,  4.38340225e-02,  8.93135835e-02,
        1.75096376e-01,  3.31549395e-01,  6.08348705e-01,  1.08472310e+00,
        1.88415368e+00,  3.19507604e+00])

4. Write the Python code to find $N$ that makes the maximum approximation error of your function for $x\in [-2\pi, 2\pi]$ less than 1.0e-10.

In [58]:
# your code here
N=1
x=np.linspace(math.pi*-2,math.pi*2,50)
while True:
    max_error=1e-10
    if max(abs(np.sin(x)-sinx(x,N)))<=max_error:
        print(N)
        break
    N+=1

15


## Q3. Geometric and Harmonic Means

1. Look up the definitioin of `geometric` and `harmonic` means and write two lambda functions to compute those using their definitions.

In [63]:
# your code here
geometric_mean = lambda x : np.exp(np.mean(np.log(x)))
harmonic_mean = lambda x :  len(x) / (1/x).sum()

2. Generate a 1-d Numpy array $X$ of 100 random integers.

In [98]:
# your code here
X =np.random.randint(1,1000,size = 100)
X

array([242, 373, 936, 636, 420, 804, 812, 336, 740, 949, 261, 837, 842,
       144, 464, 538, 270, 665, 490, 115, 588, 466, 700,  22, 743, 184,
       333, 867, 105, 625, 795, 806, 538, 917, 381, 785,  62, 233, 285,
       130, 130, 229, 738, 812, 295, 831, 336, 417, 650,  39, 532, 943,
       264,  26, 908,  98, 608, 130,  28, 363, 971, 335, 627, 977, 336,
       711, 668, 367, 168, 814, 235, 518, 876, 290, 190, 478,  24, 689,
       482, 159, 125,  78, 495, 974, 558, 793, 683,  41, 702, 121, 490,
       137, 320,  44, 747, 926, 864, 981, 126, 908])

3. Using the functions that you wrote above, compute the geometric and harmonic means of the array $X$.

In [99]:
# your code here
print(geometric_mean(X))
print(harmonic_mean(X))

354.3458522172082
190.12083191751503


4. There are aleady functions to compute the geometric and harmonic means in the `statistics` library. Use these functions, compute the geometric and harmonic means again and compare the results with those from your functions.

In [100]:
import statistics 

# your code here
print(statistics.geometric_mean(X))
print(statistics.harmonic_mean(X))

#results are almost same

354.3458522172082
190.12083191751506


## Q4. Simulation for Linear Regression

Suppose that the true relationship between the dependent variable ($y$) and three explanatory variables ($X_1$, $X_2$ and $X_3$) are given as follows: $$ y_t = 2 + 4 X_{1,t}  + 6 X_{2,t}  + 8 X_{3,t} + \epsilon_t,$$ where $\epsilon \sim N(0, 0.04)$ and  $t = 1, 2, \cdots, T$. This relationship can be written in matrix form: $\mathbf{y} = \mathbf{X}\beta$, where $\mathbf{y} = (y_1, y_2, \cdots, y_T)'$, $\mathbf{X} = (\mathbf{1}, \mathbf{X}_{1}, \mathbf{X}_{2}, \mathbf{X}_{3})$ and $\beta = (2,4,6,8)'$.

The economist does not know the true relationship but only has dataset of ($X, y$) and wants to figure out the relationship between $X$ and $y$ based on linear models. The Ordinary Least Squares (OLS) estimates of the coefficients is $$\hat{\beta} = (\mathbf{X'}\mathbf{X})^{-1}\mathbf{X'}\mathbf{y}$$


1. Create the matrix ($\mathbf{X}$) of explanatory variables assuing that:
  - the first column contains 100 ones.
  - the second column contains 100 numbers from $N(2, 5)$
  - the third column contains 100 numbers from $N(3, 3)$
  - the fourth column contains 100 numbers from $N(5, 2)$

  Check whether explanatory variables are created as specified.

In [123]:
# your code here
col1=np.ones((100,1))
col2=np.random.normal(2,5**1/2,(100,1))
col3=np.random.normal(3,3**1/2,(100,1))
col4=np.random.normal(5,2**1/2,(100,1))
X=np.concatenate((col1,col2,col3,col4),axis=1);X

array([[ 1.        ,  0.43690717,  3.29976768,  5.08522057],
       [ 1.        ,  1.15194782,  3.86983072,  5.11936642],
       [ 1.        ,  2.80781179,  2.13985524,  4.21371599],
       [ 1.        ,  1.21343928,  5.15007475,  4.68265793],
       [ 1.        , -0.18193856,  3.31262432,  5.15412742],
       [ 1.        ,  1.84451419,  3.37164826,  2.4418928 ],
       [ 1.        ,  4.61125081,  5.2353562 ,  2.61617568],
       [ 1.        ,  2.80117036,  4.63360669,  5.1539881 ],
       [ 1.        , -0.82365817, -0.71576513,  3.95089602],
       [ 1.        , -0.20653984,  3.61757539,  4.07194551],
       [ 1.        ,  5.45337879,  2.82674222,  4.79883645],
       [ 1.        ,  1.79346474,  1.96838777,  4.37568462],
       [ 1.        ,  0.20032422,  3.73684411,  3.20183218],
       [ 1.        ,  3.51729736,  1.7861767 ,  5.11880099],
       [ 1.        , -2.17102929,  2.13040922,  3.29792581],
       [ 1.        , -1.52504248,  2.7557794 ,  5.91293693],
       [ 1.        ,  6.

  2. Create the vector of dependent variable ($\mathbf{y}$) using the true relationship above.

In [124]:
# your code here
beta = np.array([2,4,6,8])
y=np.matmul(X,beta).reshape(100,1)+np.random.normal(0, 0.2,(100, 1));y

array([[ 64.01327213],
       [ 70.49037799],
       [ 59.95348233],
       [ 75.52292086],
       [ 62.43935373],
       [ 49.05410213],
       [ 72.59896378],
       [ 82.28306791],
       [ 25.80531371],
       [ 55.51189173],
       [ 79.4867604 ],
       [ 56.00877666],
       [ 50.78408736],
       [ 67.82267449],
       [ 32.45553003],
       [ 60.20556071],
       [ 90.80101927],
       [ 74.44040064],
       [ 90.17948319],
       [ 76.41545771],
       [ 78.56224857],
       [ 53.19386966],
       [ 74.3029594 ],
       [ 67.63082843],
       [ 44.9624659 ],
       [ 48.98234525],
       [ 72.21563014],
       [ 76.67733908],
       [ 77.99738823],
       [ 54.61904265],
       [ 56.51774827],
       [ 74.69515959],
       [ 65.03694946],
       [ 61.19395776],
       [ 78.4861669 ],
       [ 68.47313869],
       [100.06154979],
       [ 72.58193313],
       [ 72.09183022],
       [ 53.3715051 ],
       [ 70.99015924],
       [ 47.52427672],
       [ 96.06661898],
       [ 80

3. Compute the estimates of coefficients.

In [125]:
# your code here
np.linalg.inv((X.transpose() @ X)) @ X.transpose() @ y

array([[2.01892495],
       [4.01314629],
       [5.99404458],
       [8.0060711 ]])

4. From the OLS equation, the estimates of the coefficients, $\hat{\beta}$, can be interprested as the solution to a linear equation system. Write the linear equation system and `solve` for it.   

$$\mathbf{X'}\mathbf{y} = (\mathbf{X'}\mathbf{X})\hat{\beta}$$

In [126]:
# your code here
beta_hat = np.linalg.solve(X.transpose() @ X, X.transpose() @y);beta_hat

array([[2.01892495],
       [4.01314629],
       [5.99404458],
       [8.0060711 ]])

5. Suppose that the economist thinks that the explanaroty bariable $X_3$ is not important for the dependent variable. Hence she drop that variable from her estimation equation. Compute the estimates $\tilde{\beta}$ with this specification and explain how $\tilde{\beta}$ compare with $\hat{\beta}$.

In [127]:
# your code here
drop_X = np.delete(X, 3, axis=1)
newbeta_hat = np.linalg.solve(drop_X.transpose() @ drop_X, drop_X.transpose() @y)
print(newbeta_hat)
print()
print(beta_hat)

#coefficient of x1 is different(larger than origin one) but other coefficients are similar

[[41.82119399]
 [ 4.15565377]
 [ 5.61263953]]

[[2.01892495]
 [4.01314629]
 [5.99404458]
 [8.0060711 ]]


6. The economist is not intested in the constant term. Hence she converted her estimation model to the form of deviations from means:  $$y - \bar{y} = \left(\mathbf{X}-\mathbf{\bar{X}} \right) \gamma,$$ where $\bar{\mathbf{y}}$ and $\bar{\mathbf{X}}$ are the means of $\mathbf{y}$ and $\mathbf{X}$ respectively. Write down the OLS estimates for $\gamma$, compute $\hat{\gamma}$ and compare $\hat{\gamma}$ and $\hat{\beta}$.

In [131]:
# your code here

gamma_hat = np.linalg.pinv(X-np.mean(X,axis=0))@ (y-np.mean(y,axis=0));gamma_hat

#other coefficients are similar but beta_0(constant term) is equal to 0 in gamma_hat. and this is the main difference
#from beta_hat. Reason is that by subtarcting mean term, constant term is disappeared.

array([[0.        ],
       [4.01314629],
       [5.99404458],
       [8.0060711 ]])